# Generated by Django 5.0.6 on 2024-06-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='profile',
        ),
        migrations.AlterField(
            model_name='custommodel',
            name='profile_picture',
            field=models.FileField(blank=True, default='assets/images/user/profile-picture/user.png', null=True, upload_to='assets/images/user/profile-picture'),
        ),
    ]
