# Generated by Django 5.0.6 on 2024-06-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_remove_client_contact_number_remove_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custommodel',
            name='employee_id',
        ),
    ]
