# Generated by Django 5.0.6 on 2024-06-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_remove_custommodel_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
    ]
