# Generated by Django 5.0.6 on 2024-06-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_productionprocess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='service',
        ),
        migrations.AddField(
            model_name='package',
            name='deliverables',
            field=models.ManyToManyField(to='console.deliverables'),
        ),
    ]
