# Generated by Django 5.0.6 on 2024-06-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_remove_package_service_package_deliverables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='trash',
        ),
    ]
