# Generated by Django 5.0.6 on 2024-07-15 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0007_remove_package_trash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_member',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='team_member',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='team_member',
            name='name',
        ),
        migrations.AddField(
            model_name='team_member',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
