# Generated by Django 5.0.6 on 2024-07-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0008_remove_team_member_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='user_token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
