# Generated by Django 5.0.6 on 2024-07-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0010_team_member_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bride_Email_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='bride_date_of_birth',
            field=models.DateField(blank=True, default='0001-01-01', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='bride_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='groom_Email_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='groom_contact_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='groom_date_of_birth',
            field=models.DateField(blank=True, default='0001-01-01', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='groom_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='wedding_date',
            field=models.DateField(blank=True, default='0001-01-01', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='wedding_venue',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payments_history',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
