# Generated by Django 5.0.6 on 2024-07-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0013_reviews_booking_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
