# Generated by Django 5.0.6 on 2024-08-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0014_alter_reviews_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
