# Generated by Django 5.0.6 on 2024-08-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0015_client_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
