# Generated by Django 5.0.6 on 2024-08-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0016_useraccount_first_login_useraccount_trash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='description',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
