# Generated by Django 5.0.6 on 2024-08-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0017_team_member_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bride_Email_id',
            new_name='bride_email_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='groom_Email_id',
            new_name='groom_email_id',
        ),
    ]
