# Generated by Django 5.0.6 on 2024-09-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0018_rename_bride_email_id_booking_bride_email_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncoderDecoder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.JSONField()),
            ],
        ),
    ]
