# Generated by Django 5.0.6 on 2024-09-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0019_encoderdecoder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncoderDecoder',
        ),
    ]
