# Generated by Django 5.0.6 on 2024-09-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0020_delete_encoderdecoder'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncoderDecoder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
            ],
        ),
    ]
