# Generated by Django 5.0.6 on 2024-09-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0022_alter_reviews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund_history',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments_history',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
